// ─── هيكل المشروع والملفات ───────────────────────────────────────────────────
export const PROJECT_FILES = [
  // --- Pages ---
  {
    name: "الصفحة الرئيسية للعملاء",
    path: "src/app/page.js",
    type: "page",
    badge: "صفحة",
    badgeColor: "#3b82f6",
    desc: "لوحة التحكم للعملاء لعرض وتحليل الحسابات المالية المرفوعة عبر ملفات HTML وتعديل الأرصدة وعرض المعاملات.",
    icon: "🏠",
  },
  {
    name: "حاسبة أرضيات الحاويات",
    path: "src/app/Storagecalculator/page.jsx",
    type: "page",
    badge: "صفحة",
    badgeColor: "#3b82f6",
    desc: "حاسبة إلكترونية متطورة لحساب غرامات وأرضيات الحاويات بناءً على التواريخ، نوع الحاوية، أسعار الصرف، وفترات السماح.",
    icon: "🧮",
  },
  {
    name: "إدارة فئات الأسعار",
    path: "src/app/Storagecalculator/rates/page.jsx",
    type: "page",
    badge: "صفحة",
    badgeColor: "#3b82f6",
    desc: "صفحة مخصصة لإدارة وعرض فئات وأسعار غرامات الحاويات المختلفة ونسب الشرائح اليومية وفترات السماح لكل فئة.",
    icon: "🏷️",
  },
  {
    name: "لوحة الإدارة والتحكم",
    path: "src/app/admin/page.jsx",
    type: "page",
    badge: "صفحة",
    badgeColor: "#3b82f6",
    desc: "لوحة الإدارة الحالية لإدارة حسابات المستخدمين وأدوارهم، وتحديث سعر صرف الدولار، واستعراض هيكل ملفات المشروع والـ APIs.",
    icon: "⚙️",
  },
  {
    name: "صفحة تسجيل الدخول",
    path: "src/app/login/page.js",
    type: "page",
    badge: "صفحة",
    badgeColor: "#3b82f6",
    desc: "صفحة مصادقة وتأمين دخول المستخدمين مع التحقق من صحة البيانات وحماية الحسابات من الاختراق أو المحاولات المتكررة.",
    icon: "🔒",
  },
  // --- APIs ---
  {
    name: "جلب الحسابات",
    path: "GET /api/accounts",
    type: "api",
    badge: "API (GET)",
    badgeColor: "#10b981",
    desc: "جلب قائمة بكافة الحسابات المسجلة بقاعدة البيانات مع حجب كلمات المرور لأمان البيانات وتصنيفهم من الأحدث للأقدم.",
    icon: "📡",
  },
  {
    name: "إضافة حساب جديد",
    path: "POST /api/accounts",
    type: "api",
    badge: "API (POST)",
    badgeColor: "#10b981",
    desc: "إنشاء حساب مستخدم جديد وتأمين وحفظ كلمة المرور بعد تشفيرها تلقائياً وتحديد دوره وعدد محاولات تسجيل دخوله.",
    icon: "📡",
  },
  {
    name: "تحديث بيانات الحساب",
    path: "PUT /api/accounts/[id]",
    type: "api",
    badge: "API (PUT)",
    badgeColor: "#10b981",
    desc: "تحديث الحساب الحالي (تعديل الاسم، تغيير الرقم السري، تغيير الدور، تعديل عدد محاولات الدخول المتبقية).",
    icon: "📡",
  },
  {
    name: "حذف الحساب",
    path: "DELETE /api/accounts/[id]",
    type: "api",
    badge: "API (DELETE)",
    badgeColor: "#10b981",
    desc: "حذف حساب مستخدم معين نهائياً وبشكل كامل من قاعدة البيانات بالاعتماد على معرّفه الفريد.",
    icon: "📡",
  },
  {
    name: "تعديل محاولات الدخول",
    path: "PATCH /api/accounts/[id]/attempts",
    type: "api",
    badge: "API (PATCH)",
    badgeColor: "#10b981",
    desc: "تحديث وتصفير أو زيادة عدد محاولات الدخول المسموح بها للمستخدم بعد قفله، بحد أقصى أو قيم مخصصة.",
    icon: "📡",
  },
  {
    name: "تسجيل دخول الحساب",
    path: "POST /api/auth/login",
    type: "api",
    badge: "API (POST)",
    badgeColor: "#10b981",
    desc: "تسجيل دخول للمستخدم والتأكد من نشاط حسابه ومطابقة كلمة المرور وتوليد رمز توثيق أمني (JWT Token) مشفر كملف ارتباط.",
    icon: "📡",
  },
  {
    name: "تسجيل الخروج",
    path: "POST /api/auth/logout",
    type: "api",
    badge: "API (POST)",
    badgeColor: "#10b981",
    desc: "إلغاء جلسة المستخدم النشطة وحذف ملف تعريف ارتباط التوثيق الآمن (auth-token Cookie).",
    icon: "📡",
  },
  {
    name: "جلب البيانات المالية",
    path: "GET /api/data",
    type: "api",
    badge: "API (GET)",
    badgeColor: "#10b981",
    desc: "استرداد جميع جداول حسابات العملاء والحركات المسجلة عليها من قاعدة البيانات مرتبة بكود الحساب.",
    icon: "📡",
  },
  {
    name: "حفظ واستبدال البيانات المالية",
    path: "POST /api/data",
    type: "api",
    badge: "API (POST)",
    badgeColor: "#10b981",
    desc: "مسح كامل جداول حسابات العملاء القديمة واستبدالها بالقائمة الجديدة المرفوعة من ملفات Excel/HTML للحسابات.",
    icon: "📡",
  },
  {
    name: "جلب سعر صرف العملة",
    path: "GET /api/settings",
    type: "api",
    badge: "API (GET)",
    badgeColor: "#10b981",
    desc: "استدعاء القيمة الحالية لسعر الصرف الرسمي المسجل بالمشروع، مع توفير قيمة افتراضية في حالة عدم التسجيل.",
    icon: "📡",
  },
  {
    name: "تعديل سعر صرف العملة",
    path: "PUT /api/settings",
    type: "api",
    badge: "API (PUT)",
    badgeColor: "#10b981",
    desc: "تحديث وحفظ سعر صرف الدولار مقابل الجنيه في قاعدة البيانات لتحديث حسابات حاسبة الأرضيات فوراً.",
    icon: "📡",
  },
  // --- Libs & Models ---
  {
    name: "نموذج المستخدم (User Model)",
    path: "src/models/User.js",
    type: "core",
    badge: "قاعدة بيانات",
    badgeColor: "#818cf8",
    desc: "مخطط MongoDB لحسابات المستخدمين؛ يحتوي على البيانات الأساسية والتشفير التلقائي لكلمات المرور وتجزيئها.",
    icon: "🗄️",
  },
  {
    name: "نموذج البيانات المالية (AccountData)",
    path: "src/models/AccountData.js",
    type: "core",
    badge: "قاعدة بيانات",
    badgeColor: "#818cf8",
    desc: "مخطط MongoDB لحفظ جداول الحسابات المالية المرفوعة وسجلات العمليات المالية المسجلة محلياً عليها.",
    icon: "🗄️",
  },
  {
    name: "نموذج الإعدادات (Settings Model)",
    path: "src/models/Settings.js",
    type: "core",
    badge: "قاعدة بيانات",
    badgeColor: "#818cf8",
    desc: "مخطط MongoDB لتخزين المتغيرات العامة للنظام مثل قيمة سعر صرف الدولار المحدثة.",
    icon: "🗄️",
  },
  {
    name: "رابط قاعدة البيانات (MongoDB Lib)",
    path: "src/lib/mongodb.js",
    type: "core",
    badge: "مكتبة",
    badgeColor: "#f43f5e",
    desc: "مكتبة الربط بقاعدة بيانات MongoDB Atlas بشكل آمن مع توفير خاصية الكاش والتحقق من حالة الاتصال لتفادي تكراره.",
    icon: "🛠️",
  },
  {
    name: "محلل الملفات (HTML Parser)",
    path: "src/lib/parser.js",
    type: "core",
    badge: "مكتبة",
    badgeColor: "#f43f5e",
    desc: "معالج ذكي يقوم بقراءة ملفات HTML المحاسبية وتحويلها برمجياً إلى مصفوفات جيسون منظمة يسهل حفظها وعرضها.",
    icon: "🛠️",
  },
  {
    name: "لوجيك حاسبة الأرضيات",
    path: "src/lib/storageCalculator.js",
    type: "core",
    badge: "مكتبة",
    badgeColor: "#f43f5e",
    desc: "المكتبة الرياضية لحساب الغرامات والأرضيات المعقدة والشرائح اليومية وتواريخ انتهاء فترات السماح للحاويات.",
    icon: "🛠️",
  },
  {
    name: "ثوابت وقيم الأرضيات",
    path: "src/lib/storageConstants.js",
    type: "core",
    badge: "مكتبة",
    badgeColor: "#f43f5e",
    desc: "ملف يحتوي على ثوابت تصنيفات الحاويات (تلاجة، عادي)، وفترات السماح والأسعار الافتراضية لكل شريحة من الغرامات.",
    icon: "🛠️",
  },
  {
    name: "التوثيق والمصادقة (Auth Utils)",
    path: "src/lib/auth.js",
    type: "core",
    badge: "مكتبة",
    badgeColor: "#f43f5e",
    desc: "مكتبة مساعدة للتحقق من هوية وصلاحيات المستخدمين وتوليد رموز JWT وحماية المسارات الداخلية والمحاولات.",
    icon: "🛠️",
  },
];

// ─── ثوابت الأدوار ───────────────────────────────────────────────────────────
export const ROLES = [
  {
    value: "owner",
    label: "المالك",
    color: "#f0b429",
    bg: "rgba(240,180,41,0.12)",
  },
  {
    value: "admin",
    label: "مدير",
    color: "#818cf8",
    bg: "rgba(129,140,248,0.12)",
  },
  {
    value: "employee",
    label: "موظف",
    color: "#34d399",
    bg: "rgba(52,211,153,0.12)",
  },
  {
    value: "client",
    label: "عميل",
    color: "#60a5fa",
    bg: "rgba(96,165,250,0.12)",
  },
];

export const getRoleInfo = (v) => ROLES.find((r) => r.value === v) || ROLES[3];

// ─── نموذج فارغ ─────────────────────────────────────────────────────────────
export const EMPTY_FORM = {
  username: "",
  password: "",
  phone: "",
  role: "client",
  attempts: 5,
};
